### PR TITLE
feat: Add glint types

### PR DESCRIPTION
**Pull request by muziejus**
I've added typing so glint users can benefit from hinting and autocorrect in their templates.

### CODE REVIEW

**Comment by SergeAstapov** [comment]
@muziejus thanks for doing this! I wonder if we can have a test-app updated to utilize Glint to verify it's working fine?

**Comment by muziejus** [comment]
Sure! I'll put something together.

**Comment by muziejus** [comment]
easier said than done. I may be missing something conceptually, but it seems like the types aren't testable at build time? I've been trying to make sense of how glint does its own testing all weekend, and I'm pretty stumped, because the tests in the ember-test-app don't seem to fail.

**Comment by SergeAstapov** [comment]
Thanks @muziejus for contribution! I'll get this merged "as is" and we'll adjust if needed moving forward

**Pull request merged**
